-- *****************************************************************************
-- This script contains INSERT statements for populating tables with seed data
-- *****************************************************************************

BEGIN;

-- INSERT statements go here
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('COSI',	'COS',	'Museum',	39.959651,	-83.00659,		'333 W Broad St',	'Columbus',	'OH',	43215,	'Explore Science. Discover fun! COSI Columbus is a dynamic hands-on science center located in Central Ohio that is fun for all ages.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Columbus Zoo',	'ZOO',	'Entertainment',	40.155399,	-83.109278,		'4850 Powell Rd',	'Powell',	'OH',	43065,	'The Columbus Zoo and Aquarium is a non-profit zoo located near Powell in Liberty Township, Delaware County, Ohio, United States, north of the city of Columbus. The land lies along the eastern banks of the O''Shaughnessy Reservoir on the Scioto River, at the intersection of Riverside Drive and Powell Road. It has a worldwide reputation, largely attributable to the efforts and promotion of director emeritus Jack Hanna. In 2009, it was named by the USA Travel Guide as the number one zoo in the United States. It was also ranked number one best zoo in 2012 by Besties Readers Choice.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Zoombezi Bay',	'BAY',	'Entertainment',	40.157562,	-83.120654,		'10101 Riverside Dr',	'Powell',	'OH',	43065,	'Zoombezi Bay is a 22.7 acre water park owned by the Columbus Zoo and Aquarium near Powell, Ohio just north of Columbus. The park sits on the site of the former Wyandot Lake Amusement Park, which was purchased by the Columbus Zoo and Aquarium in 2006. Zoombezi Bay opened to the public on May 26, 2008, and currently ranks as one of the Midwest''s most popular water parks, attracting more than 400,000 visitors annually.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Schiller Park',	'SCP',	'Park',	39.941737,	-82.992176,		'1069 Jaeger St',	'Columbus',	'OH',	43206,	'Schiller Park is the second oldest park in the City of Columbus, runner up to only Goodale Park, established in 1857. Schiller Park was obtained in April 1867 for $15,000. Originally called Stewart''s Grove by the early settlers, the city bought these 23.5 acres in 1867 and Stewart''s Grove became City Park. In 1891, it was renamed Schiller park after the famous German poet, Friedrich von Schiller. An impressive statue of Schiller decorates the center of the park. During World War I, American sentiment turned against all things German and Schiller Park was renamed Washington Park. Several of the German Street names in the area also were changed. After the war, the parks name was changed back to Schiller, although most of the streets did not revert to their pre-war names (German Village Society, 1992). The park is now a well-kept central location of German Village life. The recreation center, picnic areas, softball diamonds, fishing pond and stage for the Actor''s Summer Theater, not to mention the beautifully landscaped gardens, make Schiller Park the jewel of German Village.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Goodale Park',	'GOP',	'Park',	39.975383,	-83.004769,		'120 W Goodale St',	'Columbus',	'OH',	43215,	'Goodale Park is a public park in the Victorian Village area of Columbus, Ohio. It was donated to the city in 1851 by Lincoln Goodale. For a few months during the Civil War, it was a staging area for Union troops known as Camp Jackson. ComFest, a large, free, non-corporate, music and arts annual festival, is held in the park in June.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('LeVeque Tower',	'LET',	'Entertainment',	39.962509,	-83.00198,		'50 W Broad St',	'Columbus',	'OH',	43215,	'LeVeque Tower is a 47-story Art Deco-style building in Columbus. Located at 50 West Broad Street, it was the tallest building in Columbus from 1927 until 1974 when the Rhodes State Office Tower was completed. The LeVeque Tower is 555 feet 6 inches (169.32 m) tall, which at the time of its completion made it the tallest building between New York City and Chicago and the fifth tallest building in the world. It was meant to be built exactly one half foot taller than the Washington Monument in Washington D.C. Originally the two wings of the building were used as a 600-room addition for the Deshler-Wallick Hotel, the city''s leading hotel at the time and one of the world’s largest. Throughout its history the building has been noted for the bright and elaborate lighting of its tower. The original design placed the signal lights on the four turrets of the tower. Since the 1980s the tower has had the capability of being lit in a variety of colors. It is normally lit in white, but color is added frequently for special occasions. LeVeque Tower complex continues to be home to a variety of businesses and offices, including, at its base, the Palace Theatre.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Polaris Fashion Place',	'PFP',	'Shopping',	40.14147,	-82.978953,		'1500 Polaris Pkwy',	'Columbus',	'OH',	43240,	'Polaris Fashion Place is a two level shopping mall and surrounding retail plaza serving Columbus, Ohio, United States. The mall, owned locally by WP Glimcher, is located off Interstate 71 on Polaris Parkway in Delaware Countyjust to the north of the boundary between Delaware and Franklin County. The mall features eight anchor stores: H&M, J.C. Penney, Macy''s, Saks Fifth Avenue, Sears, Von Maur, Dick''s Sporting Goods, and Field & Stream (retailer), as well as an outdoor promenade which includes XXI Forever and Barnes & Noble.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Easton Town Center',	'ETC',	'Shopping',	40.051,	-82.914968,		'160 Easton Town Center',	'Columbus',	'OH',	43219,	'Easton Town Center ("Easton") is an indoor and outdoor shopping complex in northeast Columbus, Ohio, United States. The core buildings and streets that comprise Easton are intended to look like a self-contained "town", reminiscent of American towns and cities in the early-to-mid 20th century. Included in the design are fountains, streets laid out in a grid pattern surrounded by a continuous loop, and metered storefront parking. A variety of stores, restaurants, and service-oriented businesses occupy structures of varying sizes, most of which are contiguous, having shared walls. Many of these structures have a similar external appearance. Also included are traditional shopping mall features like large, multi-floor department stores, small kiosks located in the indoor common areas, a cinema complex, ATMs, and both covered and open parking structures. Easton attracts roughly 25 million visitors per year.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Ohio Theatre',	'OHI',	'Theater',	39.960068,	-82.99889,		'39 E State St',	'Columbus',	'OH',	43215,	'The Ohio Theatre is a performing arts center located at 39 E. State Street in Columbus. Known as the "Official Theatre of the State of Ohio", the historic 1928 movie palace was saved from demolition in 1969 and completely restored. It was declared a National Historic Landmark in 1977. The Ohio Theatre is owned and operated by the non-profit arts management organization CAPA (The Columbus Association for the Performing Arts), which was originally formed to save the theater in 1969. The executive director is Bill Connor. The Ohio Theatre was one of the earliest restorations of a movie palace for use as a performing arts center and served as a model for many later historic renovation projects in the United States. Unlike many remaining 1920s theaters designed by Lamb and others, the Ohio still very closely resembles its original appearance with only a few modern additions. Today it is the home of the Columbus Symphony Orchestra, BalletMet, the Broadway Series, Opera Columbus, and the CAPA Summer Movie Series.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Palace Theatre',	'PAT',	'Theater',	39.962317,	-83.001705,		'34 W Broad St',	'Columbus',	'OH',	43215,	'The Palace Theatre is a 2,827-seat restored movie palacelocated at 34 W. Broad Street in Columbus, Ohio. It was designed and built in 1926 by the American architect Thomas W. Lamb as part of the American Insurance Union Citadel (now LeVeque Tower). Today the theater functions as a multi-use performing arts venue. It is owned and operated by The Columbus Association for the Performing Arts. The Palace Theaters "house" is considered separate from LeVeque Tower, while the Marquee and lobby are part of the Leveque complex.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Mapfre Stadium',	'MAS',	'Sports',	40.008995,	-82.99122,		'One Black & Gold Blvd',	'Columbus',	'OH',	43211,	'Mapfre Stadium previously known as Columbus Crew Stadium, is a soccer-specific stadium in Columbus, Ohio, United States. It primarily serves as the home stadium of the Columbus Crew SC of Major League Soccer. Mapfre Stadium is also the site of a variety of additional events in amateur and professional soccer, American football, lacrosse, and rugby, and is a regular site for outdoor concerts due to the permanent stage in the north end zone.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Ohio Stadium',	'OHS',	'Sports',	40.001645,	-83.019727,		'411 Woody Hayes Dr',	'Columbus',	'OH',	43210,	'Ohio Stadium, also known as the Horseshoe, "the Shoe", and "the House that Harley", is an American football stadium in Columbus, Ohio, United States, on the campus of The Ohio State University. Its primary purpose is the home venue of the Ohio State Buckeyes football team and the Ohio State University Marching Band. From 1996 to 1998, Ohio Stadium was the home venue for the Columbus Crew of Major League Soccer prior to the opening of Columbus Crew Stadium in 1999. The stadium also was the home venue for the OSU track and field teams from 1923–2001. In addition to athletics, Ohio Stadium is also a concert venue, with U2, The Rolling Stones, Pink Floyd, and Metallica among the many acts to have played there, and also serves as the site for the university''s Spring Commencement ceremonies each May. Permanent field lights were added in 2014.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Ohio Statehouse',	'OSH',	'Government',	39.961633,	-82.998954,		'1 Capitol Square',	'Columbus',	'OH',	43215,	'The Ohio Statehouse, located in Columbus is the house of government. The Greek Revival building houses the Ohio General Assembly and the ceremonial offices of the Governor, Lieutenant Governor, Treasurer, and Auditor. The Statehouse features a central recessed porch with a colonnade of a forthright and primitive Greek Doric mode, built of Columbus limestone that was quarried on the west banks of the Scioto River. A broad and low central pediment supports the windowed astylar drum, referred to as a Cupola, which contains an occulus that lights the interior rotunda. The Statehouse contains many large scale art works both within the walls and on the grounds of the building. There are a great number of portraits of Governors and Lt. Governors contained in hearing rooms and offices throughout the building, and in public spaces there are several large scale artworks that memorialize individuals or events significant to the state or the nation. The Ohio Statehouse functions both as a working government building that contains the activities of a legislature and governors office, and as a museum.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Franklin Park Conservatory',	'FPC',	'Park',	39.965849,	-82.953303,		'1777 E Broad St',	'Columbus',	'OH',	43203,	'Franklin Park Conservatory and Botanical Gardens is a botanical garden and conservatory located in Columbus, Ohio. It is open daily and an admission fee is charged. Originally built in 1895, the Conservatory is on the National Register of Historic Places. Today, it is a horticultural and educational institution showcasing exotic plant collections, special exhibitions, and Dale Chihuly artworks.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Ohio History Center',	'OHC',	'Museum',	40.004847,	-82.987425,		'800 E 17th Ave',	'Columbus',	'OH',	43211,	'Ohio History Connection operates dozens of state historic sites across Ohio. Its headquarters is the 250,000-square-foot (23,000 square m) Ohio History Center in Columbus, Ohio, a Brutalist concrete structure. Extensive exhibits cover Ohios history from the Ice Age to the present. The Center includes state archives and library spaces, a gift shop, and administrative and educational facilities. The 1989 Smithsonian Guide to Historic America described the Center as "probably the finest museum in America devoted to pre-European history."');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Lincoln Theatre',	'LIT',	'Theater',	39.966969,	-82.98064,		'769 E Long St',	'Columbus',	'OH',	43203,	'The fully renovated, historic Lincoln Theatre is a multi-use, state-of-the-art performing arts center designed to engage, educate, and entertain the community. With a capacity of 588 seats, the Lincoln Theatre is an intimate venue perfect for any event. Since it''s reopening in May 2009, the stage of the Lincoln has been host to musical performances, corporate meetings, stage plays, movie screenings, weddings and cocktail receptions.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Columbus Museum of Art',	'CMA',	'Museum',	39.964207,	-82.987897,		'480 E Broad St',	'Columbus',	'OH',	43215,	'The newly renovated and expanded Columbus Museum of Art opened on Oct. 24. Great experiences with great art for everyone! We believe that art speaks to each and every one of us in different ways. Art inspires. Art challenges. Art thinks. Visit our website for current exhibition schedule. Cell phone tours available. Schedule "experiential tours" by appointment at 614-221-6801.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Wexner Center for the Arts',	'WEC',	'Museum',	40.000683,	-83.009308,		'1871 N High St',	'Columbus',	'OH',	43210,	'The Wexner Center for the Artsis The Ohio State University''s multidisciplinary, international laboratory for the exploration and advancement of contemporary art. Through exhibitions, screenings, performances, artist residencies, and educational programs, the Wexner Center acts as a forum where established and emerging artists can test ideas and where diverse audiences can participate in cultural experiences that enhance understanding of the art of our time. In its programs, the Wexner Center balances a commitment to experimentation with a commitment to traditions of innovation and affirms the university''s mission of education, research, and community service. The Wexner Center opened in November 1989, named in honor of the father of Limited Brands founder Leslie Wexner, who was a major donor to the Center.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Park of Roses',	'POR',	'Park',	40.041508,	-83.019376,		'3901 N High St',	'Columbus',	'OH',	43214,	'Located in Clintonville, the Park of Roses is one of the most unique and renown parks in the state of Ohio. In existence since 1953, visiting the park during the Rose Festival has become a time honored tradition for Ohioans statewide. The Columbus Park of Roses is a 13-acre plot in Whetstone Park that showcases 11,000 total roses consisting of more than 350 different types. In addition to visually stunning roses, the park features many gardens: the Main Rose Garden, the Heritage Garden with turn of the century roses, the Earth-Kind Rose Garden, the Herb Garden, and the Perennial Garden. Throughout the past 56 years, the Columbus Rose Park has garnered many honors, including being one of 133 All American Rose Selection gardens, selected as one of USA Todays 10 Places to Admire the Bloom on the Rose in 2006, and being one of Columbus'' top wedding venues. The park is open daily from dawn until dusk, and admission to all visitors is free. The best time to view the roses is during their full bloom which begins in mid-June and lasts through mid-September.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Scioto Mile',	'SCM',	'Park',	39.956723,	-83.003568,		'233 S Civic Center Dr',	'Columbus',	'OH',	43215,	'Stretching along the downtown Columbus riverfront from the vibrant Arena District on the north end to the natural beauty of the Whittier Peninsula on the south, the Scioto Mile is comprised of more than 145 acres of lush parkland, fountains, scenic overlooks and a riverfront promenade. Part of the Columbus Recreation and Parks Department, the Scioto Mile plays an essential role in the revitalization of downtown by offering a vibrant place for people to gather. Downtown Columbus is the heart of central Ohio, and the core of our Capital City. It is the business, cultural, arts and government center of central Ohio. It is the place where our community comes together to work, enrich our minds, exercise our bodies, relax and play. When downtown is strong and vibrant, we all are proud to call it our home.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('The Greater Columbus Convention Center',	'CCC',	'Entertainment',	39.97168,	-83.00113,		'400 N High St',	'Columbus',	'OH',	43215,	'The Greater Columbus Convention Center is in the center of the country, the center of Ohio, the center of Columbus, and it''s surrounded by restaurants, shops, hotels and entertainment venues. Inside, the Convention Center has 1.7 million square feet of flexible, customizable space.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Huntington Park',	'HUP',	'Sports',	39.968667,	-83.010974,		'330 Huntington Park Ln',	'Columbus',	'OH',	43215,	'Huntington Park is baseball stadium located in Columbus, Ohio, United States. It primarily serves as the home of the Columbus Clippers of the International League, the Triple-A minor league affiliate of the Cleveland Indians since 2009.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Nationwide Arena',	'NAA',	'Sports',	39.969351,	-83.006385,		'200 W Nationwide Blvd',	'Columbus',	'OH',	43215,	'Nationwide Arena is a large multi-purpose arena, in Columbus, Ohio, United States. Since completion in 2000, the arena has served as the home of the Columbus Blue Jackets of the National Hockey League.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Schottenstein Center',	'SCC',	'Sports',	40.007526,	-83.025097,		'555 Borror Dr',	'Columbus',	'OH',	43210,	'The Jerome Schottenstein Center is a multi-purpose arena, located on the campus of Ohio State University, in Columbus, Ohio, United States. It was the main sports, music, and entertainment arena in the Columbus, Ohio metropolitan area until Nationwide Arena opened in 2000. ');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Express Live',	'EXL',	'Entertainment',	39.969817,	-83.010041,		'405 Neil Ave',	'Columbus',	'OH',	43215,	'EXPRESS LIVE! is the first indoor and outdoor concert venue in America. EXPRESS LIVE! features state-of-the-art lighting, acoustical systems and an innovative, one-of-a-kind reversible stage. Entertaining over 275,000 people each year, the venue accomodates 2,200 guests for indoor events and 5,200 guests for outdoor events. Whether indoor or out, the venue offers unparalleled viewable intimacy. Acoustically, it''s designed to capture and translate the truest experience possible. Structurally, it''s divided into three independent concert spaces: indoor music hall, outdoor amphitheater and the plaza. The venues unique design flexibility helped win a nomination for "Best New Major Concert Venue" in 2001 by Pollstar Magazine, the concert industry''s leading publication.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('SuperChef''s',	'SUP',	'Restaurant',	40.054411,	-82.885274,		'1344 Cherry Bottom Rd',	'Gahanna',	'OH',	43230,	'Childhood friends Ryan Bryson and Darnell Ferguson opened the first SuperChef’s Breakfast during the summer of 2012 in Louisville, KY. Focusing on intense flavors, vibrant palettes, great customer service, and creative presentations, SuperChef''s Breakfast & More will bring back excitement to the most important meal of the day.' );
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Los Guachos',	'LOG',	'Restaurant',	40.064617,	-83.057396,		'5221 Godown Rd',	'Columbus',	'OH',	43235,	'The best taco al pastor in the city! We are not the only ones, but we are the authentics! (No somos los unicos pero si los autenticos!) Also, try our quesadillas, tortas, tacos, grigas, alambres, huaraches too. Pork, tripa, beef tongue, stemead beef and chicken. Catering services also.');
INSERT INTO landmarks (name, landmark_id, type, latitude, longitude, street_address, city, state, zip, description) VALUES ('Skillet',	'SKI',	'Restaurant',	39.944467,	-82.985941,		'410 E Whittier St',	'Columbus',	'OH',	43206,	'Our restaurant features local products and local flavors by working with a dedicated network of farmers, producers, and craftsmen. We allow the seasons and what is available to us daily to drive our menu and in doing so it will change often. We may sell through a menu item due to the sometimes limited nature of what is procured for that particular menu offering. We do however, promise that all items served will be fresh and with Chef''s highest standards.'  );

INSERT INTO hotels (name, location_id, street_address, city, state, zip, latitude, longitude) VALUES('Courtyard Columbus Downtown',	'CCD',	'35 W Spring St',	'Columbus',	'OH',	43215,	39.965741,	-83.002793);
INSERT INTO hotels (name, location_id, street_address, city, state, zip, latitude, longitude) VALUES('Homewood Suites by Hilton Polaris',	'HSP',	'2045 Polaris Pkwy',	'Columbus',	'OH',	43240,	40.143805,	-82.9618);
INSERT INTO hotels (name, location_id, street_address, city, state, zip, latitude, longitude) VALUES('The Blackwell',	'THB',	'2110 Tuttle Park Pl',	'Columbus',	'OH',	43210,	40.004871,	-83.016261);
INSERT INTO hotels (name, location_id, street_address, city, state, zip, latitude, longitude) VALUES('Hampton Inn & Suites University Area',	'HIS',	'3160 Olentangy River Rd',	'Columbus',	'OH',	43202,	40.025428,	-83.024906);
INSERT INTO hotels (name, location_id, street_address, city, state, zip, latitude, longitude) VALUES('Drury Inn & Suites Columbus Convention Center',	'DIS',	'88 E Nationwide Blvd',	'Columbus',	'OH',	43215,	39.969771,	-82.999478);

INSERT INTO users (user_name, password, salt, user_role) VALUES('hilary', 'password','SDJydqT014UpMj7hCx+1/aeV7HJ82PA+CxZm0BeelT75HfxhbnAH/w5AVIHoX+A6eGiyzIMPflQlLiYhQxtB8LqddoMPWIW6jsX3MrjuKZKlRdd52az4DXdV3jWzFb+CwkGjVlLZ0SE/NvNmMxoEcwKPEEnGevnkZ8T0ZJJdh/s=', 'admin' );
INSERT INTO users (user_name, password, salt, user_role) VALUES('keith', 'password', 'SDJydqT014UpMj7hCx+1/aeV7HJ82PA+CxZm0BeelT75HfxhbnAH/w5AVIHoX+A6eGiyzIMPflQlLiYhQxtB8LqddoMPWIW6jsX3MrjuKZKlRdd52az4DXdV3jWzFb+CwkGjVlLZ0SE/NvNmMxoEcwKPEEnGevnkZ8T0ZJJdh/s=','cityuser');
INSERT INTO users (user_name, password, salt, user_role) VALUES('ryan', 'password','SDJydqT014UpMj7hCx+1/aeV7HJ82PA+CxZm0BeelT75HfxhbnAH/w5AVIHoX+A6eGiyzIMPflQlLiYhQxtB8LqddoMPWIW6jsX3MrjuKZKlRdd52az4DXdV3jWzFb+CwkGjVlLZ0SE/NvNmMxoEcwKPEEnGevnkZ8T0ZJJdh/s=', 'cityuser');

INSERT INTO landmark_reviews (landmark_id, user_name, thumbs_up, review_text) VALUES('ZOO', 'hilary', true, 'fake review');

ALTER TABLE landmark_reviews ADD FOREIGN KEY (landmark_id) REFERENCES landmarks(landmark_id);
ALTER TABLE landmark_reviews ADD FOREIGN KEY (user_name) REFERENCES users(user_name);
ALTER TABLE users_itinerary  ADD FOREIGN KEY (user_name) REFERENCES users(user_name);
ALTER TABLE users_itinerary  ADD FOREIGN KEY (itinerary_id) REFERENCES itinerary(itinerary_id);
ALTER TABLE itinerary_landmarks ADD FOREIGN KEY (itinerary_id) REFERENCES itinerary(itinerary_id);
ALTER TABLE itinerary_landmarks ADD FOREIGN KEY (landmark_id) REFERENCES landmarks(landmark_id);

COMMIT;